# Generated by Django 5.1.4 on 2025-01-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('platform', models.CharField(max_length=4, verbose_name='Plataforma')),
                ('score', models.IntegerField(verbose_name='Puntaje')),
                ('image', models.CharField(max_length=300, verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('route', models.CharField(max_length=300, verbose_name='Ruta')),
                ('game', models.IntegerField(primary_key=True, serialize=False, verbose_name='Game Id')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('name', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Nombre')),
            ],
        ),
    ]
