# Generated by Django 5.1.4 on 2025-01-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_game_thumbnail_alter_game_platform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-score'], 'verbose_name': 'Juego', 'verbose_name_plural': 'Juegos'},
        ),
    ]
