# Generated by Django 5.1.4 on 2025-01-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_game_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='game',
            name='video',
            field=models.TextField(null=True, verbose_name='Video'),
        ),
    ]
