# Generated by Django 5.1.4 on 2025-01-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_game_description_game_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
