# Generated by Django 5.1.4 on 2025-01-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_platform_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='slug',
        ),
    ]
