# Generated by Django 5.1.4 on 2025-01-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_platform_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
