# Generated by Django 5.1.4 on 2025-01-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_game_slug_platform_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='game',
            name='video',
            field=models.TextField(blank=True, null=True, verbose_name='Video'),
        ),
    ]
