# Generated by Django 5.1.4 on 2025-01-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_game_description_alter_game_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='name_desc',
            field=models.CharField(blank=True, max_length=25, verbose_name='Nombre descriptivo'),
        ),
    ]
