# Generated by Django 5.1.4 on 2025-01-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_platform_name_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='name_desc',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre descriptivo'),
        ),
    ]
