# Generated by Django 5.1.4 on 2025-01-17 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_platform_name_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
